name: tests
run-name: ${{ github.actor }} is running tests
on: [push, pull_request]
env:
  GO_MINIMUM_VERSION: '1.22.2'
jobs:
  go_minimum:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.0.0
        with:
          go-version: ${{ env.GO_MINIMUM_VERSION }}
      - run: go test ./...
  go_latest:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-go@v5.0.0
       with:
         go-version: ${{ env.GO_MINIMUM_VERSION }}
         check-latest: true
     - run: go test ./...
